version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
